### ISSUE TITLE
Vanillaurn: get right outlet bang one before the last set of numbers

### ISSUE THREAD

**Issue by donnerbono** [alexdrymonitis/miscellaneous_abstractions#1] opened 2022-12-19 16:52 UTC
I'll have a look at trying to fix, but thought even with this being 6 years old it might be quicker as you'll know what you're doing better than me. For clarity, I get double number between the right outlet bangs but there's no repetition of you take the number after the bang and the n-1 before.

**Comment by alexdrymonitis** [comment] 2022-12-21 08:17
I can't reproduce this. You mean that some number repeats before all numbers are exhausted? What size do you use for the argument or the right inlet of the abstraction?

**Comment by donnerbono** [comment] 2022-12-21 08:26
Thanks for reply. I use vanillaUrn 8 and it does 8 unique numbers in order but the bang from the right outlet is before the last number of the set not after. I was presuming it was just an order thing?

urn: 4
urn: 7
urn: 3
urn: 2
urn: 0
urn: 4
urn: 6
urn: 5
urn: bang
urn: 1
urn: 3
urn: 7
urn: 6
urn: 4
urn: 1
urn: 0
urn: 5
urn: bang
urn: 2

**Comment by alexdrymonitis** [comment] 2022-12-21 09:13
Yes, you're right. I fixed it and uploaded it now. Thanks for pointing it out. Closing this issue.

**Closed as completed by alexdrymonitis** 2022-12-21 09:13 UTC

**Comment by donnerbono** [comment] 2022-12-21 09:52
Thank you! Reminded me to get your book out again to have a flick through over the holiday break. Cheers :)
